import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from src.models.base import Base


# ── Enumerations ─────────────────────────────────────────────────────────────────

class SectorEnum(enum.Enum):
    HUMAN = "human"
    ANIMAL = "animal"
    ENVIRONMENT = "environment"


class GuidanceStatusEnum(enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"


# ── Core AMR Record ───────────────────────────────────────────────────────────────

class AMRRecord(Base):
    """
    Central One Health isolate record. Aligned with WHO GLASS and HL7 FHIR.
    Covers human clinical, veterinary/poultry, and environmental sectors.
    """
    __tablename__ = "amr_records"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    # ── One Health Dimensions ───────────────────────────────────────────────────
    sector = Column(Enum(SectorEnum), nullable=False, index=True)
    pathogen_name = Column(String, nullable=False, index=True)      # e.g., "MDR E. coli"
    antimicrobial_agent = Column(String, nullable=False)            # e.g., "Ciprofloxacin"

    # ── Location & Source ───────────────────────────────────────────────────────
    county = Column(String, nullable=False, index=True)
    sub_county = Column(String, nullable=True)
    facility_type = Column(String, nullable=True)                   # e.g., "Tertiary Hospital", "Poultry Farm"

    # ── Resistance Profile ──────────────────────────────────────────────────────
    result_value = Column(String, nullable=False)                   # SIR: "Resistant", "Intermediate", "Sensitive"
    mic_value = Column(Float, nullable=True)

    # ── Data Integrity ──────────────────────────────────────────────────────────
    is_synthetic = Column(Integer, default=1)                       # 1=synthetic, 0=real
    data_quality_score = Column(Float, default=1.0)
    missing_fields = Column(JSON, nullable=True)                    # Tracks imputed fields

    # ── Interoperability Metadata ───────────────────────────────────────────────
    hl7_fhir_id = Column(String, nullable=True)
    woah_reference = Column(String, nullable=True)

    # ── Genomic Metadata (Module 2 Placeholders) ────────────────────────────────
    ncbi_tax_id = Column(Integer, index=True, nullable=True)
    sequencing_platform = Column(String(100), nullable=True)
    assembly_id = Column(String(100), nullable=True)
    accession_number = Column(String(100), nullable=True)
    qc_status = Column(String(50), nullable=True)

    # ── Relationships ───────────────────────────────────────────────────────────
    genomic_signals = relationship("GenomicSignal", back_populates="record")
    alerts = relationship("Alert", back_populates="record")


# ── Bioinformatics Signal ─────────────────────────────────────────────────────────

class GenomicSignal(Base):
    """Component A extension: bioinformatics integration for resistance gene tracking."""
    __tablename__ = "genomic_signals"

    id = Column(Integer, primary_key=True, index=True)
    record_id = Column(Integer, ForeignKey("amr_records.id"), nullable=False)
    resistance_genes = Column(JSON)                                 # e.g., {"blaCTX-M-15": "detected"}
    sequencing_platform = Column(String)

    record = relationship("AMRRecord", back_populates="genomic_signals")


# ── AI Alert ─────────────────────────────────────────────────────────────────────

class Alert(Base):
    """
    Component B output: persisted when IsolationForest flags a credible anomaly
    (anomaly_score < 0 AND data_quality_score > 0.7).
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    amr_record_id = Column(Integer, ForeignKey("amr_records.id"), nullable=False)
    detection_timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    # ── Anomaly Scoring ─────────────────────────────────────────────────────────
    anomaly_score = Column(Float, nullable=False)                   # IsolationForest decision_function score
    hotspot_magnitude = Column(Float, nullable=False)              # Normalized severity: higher = more severe

    # ── Explainability (SHAP stub → real-SHAP ready) ────────────────────────────
    feature_importance = Column(JSON, nullable=True)               # {"county_weight": 0.4, "pathogen_risk_weight": 0.35, ...}

    # ── Relationships ───────────────────────────────────────────────────────────
    record = relationship("AMRRecord", back_populates="alerts")
    guidance = relationship("Guidance", back_populates="alert")


# ── LLM Guidance ─────────────────────────────────────────────────────────────────

class Guidance(Base):
    """
    Component C output: role-gated advisory brief generated by LLMAdvisoryEngine
    (Claude API). Linked 1:many to an Alert (one brief per user role).
    """
    __tablename__ = "guidance"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(Integer, ForeignKey("alerts.id"), nullable=False)
    generation_timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    # ── Role-Gated Content ──────────────────────────────────────────────────────
    role_target = Column(String, nullable=False)                      # "National Coordinator" | "County Veterinarian"
    content_markdown = Column(Text, nullable=False)                 # Full markdown brief from Claude

    # ── Generation Provenance ───────────────────────────────────────────────────
    status = Column(
        String(50),
        default="PENDING",
        nullable=False,
    )

    # ── Relationships ───────────────────────────────────────────────────────────
    alert = relationship("Alert", back_populates="guidance")
