"""add_user_profile_cols_deleted_at_scheduled_reports

Revision ID: 2faff4d157f9
Revises: 43a37c09dba7
Create Date: 2026-06-20 13:59:46.856568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faff4d157f9'
down_revision: Union[str, Sequence[str], None] = '43a37c09dba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('amr_isolate_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_amr_isolate_records_deleted_at'), 'amr_isolate_records', ['deleted_at'], unique=False)
    op.add_column('guidance_briefs', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('county', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_county'), 'users', ['county'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_county'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'county')
    op.drop_column('users', 'name')
    op.drop_column('guidance_briefs', 'generated_at')
    op.drop_index(op.f('ix_amr_isolate_records_deleted_at'), table_name='amr_isolate_records')
    op.drop_column('amr_isolate_records', 'deleted_at')
    op.drop_table('scheduled_reports')
    # ### end Alembic commands ###
